title:             ಶ್ರೀDHAर
name:              Shridhar Hegde
email:             iamshridharhegde@gmail.com
descriptiona:      Developer - Engineer
descriptionb:      Here you can find some articles written by me and look at my resume. Work with me on an awesome project or hire me !
author:            Shridhar Hegde
baseurl:           ""
url:               "http://shridhar-hegde.github.io"

# Social Profiles
linkedin_username: shridhar-hegde-17698295
twitter_username:  ishridharhegde
github_username:   shridhar-hegde
facebook_username: shridhar.hegde.397
instagram_username: ishridharhegde


#Embedded Comments
talkyard_server_url: https://comments-for-shridharhegde-tk.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js


# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
